[book]
authors = ["Nikolay Plekhanov"]
language = "en"
src = "src"
title = "Fyrox Lite / C#"

#[output.html]
#no-section-label = true

[output.html]
additional-js = ["src/custom.js"]
mathjax-support = true
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-icon = "fa-github"
site-url = "/kkolyan.github.io/"
git-repository-url = "https://github.com/kkolyan/fyrox_lite"

[output.html.fold]
enable = true
level = 7
