[package]
name = "fyrox-lite"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
lite-macro = { workspace = true }
lite-runtime = { workspace = true }

[features]
default = ["fyrox/default"]
engine-dylib = ["fyrox/dylib"]