name: Debug 001

on:
  workflow_dispatch:
  # This allows running it on any branch manually:
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

env:
  CARGO_TERM_COLOR: always

jobs:

  publish_linux:
    name: Debug
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@nightly
      # Caching must be after toolchain selection
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - name: Debug
        run: |
          echo nightly-$(date +%F)$(echo "${{ github.sha }}" | cut -c1-7)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
