name: github pages

on:
  push:
    branches:
      - main
    paths:
      - 'www/**'
      - 'README.md'
  pull_request:

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Clean
        run: rm -rf ./www/public

      - name: Build the hub
        run: mdbook build ./www/hub && cp -r ./www/hub/book ./www/public

      - name: Build the book for C#
        run: mdbook build ./www/fyrox_cs && cp -r ./www/fyrox_cs/book ./www/public/fyrox_cs

      - name: Build the book for Lua
        run: mdbook build ./www/fyrox_lua && cp -r ./www/fyrox_lua/book ./www/public/fyrox_lua

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www/public