name: Publish

on:
  workflow_dispatch:
  # This allows running it on any branch manually:
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

env:
  CARGO_TERM_COLOR: always

jobs:

  package_windows:
    name: Package Windows
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@nightly
      # Caching must be after toolchain selection
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Package (C#)
        run: |
          &"C:\Program Files\Git\bin\bash.exe" -c "./bash/cs_package.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package (Lua)
        run: |
          &"C:\Program Files\Git\bin\bash.exe" -c "./bash/lua_package.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: package-windows
          path: target/*.zip

  package_macos:
    name: Package MacOS
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@nightly
      # Caching must be after toolchain selection
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Package (C#)
        run: |
          chmod -R +x bash && ./bash/cs_package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package (Lua)
        run: |
          chmod -R +x bash && ./bash/lua_package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: package-macos
          path: target/*.zip

  package_linux:
    name: Package Linux
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: sudo apt-get update && sudo apt-get install -y librust-alsa-sys-dev libdbus-1-dev pkg-config
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@nightly
      # Caching must be after toolchain selection
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Package (C#)
        run: |
          chmod -R +x bash && ./bash/cs_package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package (Lua)
        run: |
          chmod -R +x bash && ./bash/lua_package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: package-linux
          path: target/*.zip

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package-linux
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: package-windows
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: package-macos
          path: .
      - run: |
          gh release create nightly-$(date +%F)-$(echo "${{ github.sha }}" | cut -c1-7) *.zip
