name: Publish

on:
  workflow_dispatch:
  # This allows running it on any branch manually:
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

env:
  CARGO_TERM_COLOR: always

jobs:

  publish_windows:
    name: Publish Windows
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@nightly
      # Caching must be after toolchain selection
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish (C#)
        run: |
          &"C:\Program Files\Git\bin\bash.exe" -c "./bash/cs_publish.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish (Lua)
        run: |
          &"C:\Program Files\Git\bin\bash.exe" -c "./bash/lua_publish.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_macos:
    name: Publish MacOS
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@nightly
      # Caching must be after toolchain selection
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish (C#)
        run: |
          chmod -R +x bash && ./bash/cs_publish.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish (Lua)
        run: |
          chmod -R +x bash && ./bash/lua_publish.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_linux:
    name: Publish Linux
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: sudo apt-get update && sudo apt-get install -y librust-alsa-sys-dev
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@nightly
      # Caching must be after toolchain selection
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish (C#)
        run: |
          chmod -R +x bash && ./bash/cs_publish.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish (Lua)
        run: |
          chmod -R +x bash && ./bash/lua_publish.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
